services:
  postgres:
    image: "bitnami/postgresql:16"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=pass
      - POSTGRESQL_DATABASE=starter
    volumes:
      - "postgres_data:/bitnami/postgresql"

  redis:
    image: "bitnami/redis:6.2"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=pass
    volumes:
      - "redis_data:/bitnami"

  rabbitmq:
    image: "bitnami/rabbitmq:3.12"
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: tasks
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_CONF_FILE: /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq/mnesia
      - ./rabbitmq.conf:/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf


  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
