[project]
name = "starter"
version = "0.1"
description = "Backend starter using Python."
authors = [{ name = "Aryan Iyappan", email = "aryaniyappan2006@gmail.com" }]
dependencies = [
    "falcon>=3.1.1",
    "uvicorn>=0.24.0.post1",
    "sqlalchemy>=2.0.23",
    "pydantic[email]>=2.5.1",
    "argon2-cffi>=23.1.0",
    "pydantic-settings>=2.1.0",
    "alembic>=1.12.1",
    "asyncpg>=0.29.0",
    "redis>=5.0.1",
]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "AGPL-3.0" }

[tool.pdm.dev-dependencies]
test = ["pytest>=7.4.3", "pytest-asyncio>=0.21.1", "pytest-xdist>=3.5.0"]
