[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Aryan Iyappan", email = "aryaniyappan2006@gmail.com"},
]
dependencies = [
    "falcon>=3.1.1",
    "uvicorn>=0.24.0.post1",
    "sqlalchemy[postgresql_asyncpg]>=2.0.23",
    "pydantic[email]>=2.5.1",
    "argon2-cffi>=23.1.0",
    "aioredis>=2.0.1",
    "pydantic-settings>=2.1.0",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.3",
]
