name: lint

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - deptry app
          - mypy .
          - black --check .
          - ruff check .

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install PDM
        run: pip install --no-cache pdm

      - name: Install Dependencies
        run: pdm install -G dev

      - name: run ${{ matrix.job }}
        run: pdm run ${{ matrix.job }}
