name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      SERVER_DEBUG: true
      SERVER_LOG_LEVEL: "INFO"
      SERVER_DATABASE_URL: "postgresql+asyncpg://user:pass@localhost:5432/starter"
      SERVER_DATABASE_POOL_SIZE: 20
      SERVER_CORS_ALLOW_ORIGINS: '["*"]'
      SERVER_SERVER_URL: 'http://localhost:8000'
      SERVER_OPENAPI_URL:
      SERVER_REDIS_URL: "redis://:pass@localhost:6379/1"
      SERVER_SAQ_BROKER_URL: "redis://:pass@localhost:6379/2"
      SERVER_SAQ_CONCURRENCY: 10
      SERVER_EMAIL_HOST: "localhost"
      SERVER_EMAIL_PORT: 1025
      SERVER_EMAIL_USERNAME:
      SERVER_SERVER_EMAIL_PASSWORD:
      SERVER_EMAIL_FROM: "noreply@example.com"
      SERVER_GEOLITE2_DATABASE_PATH: ""
      SERVER_GOOGLE_CLIENT_ID: "client-id"
      SERVER_GOOGLE_CLIENT_SECRET: "client-secret"
      SERVER_SENTRY_DSN: ""


    services:
        postgres:
            image: "bitnami/postgresql:16"
            ports:
              - "5432:5432"
            env:
                POSTGRESQL_USERNAME: "user"
                POSTGRESQL_PASSWORD: "pass"
                POSTGRESQL_DATABASE: "starter"

        redis:
            image: "bitnami/redis:6.2"
            ports:
                - "6379:6379"
            env:
                REDIS_PASSWORD: "pass"


        mailhog:
            image: mailhog/mailhog:v1.0.1
            ports:
                - "1025:1025"
                - "8025:8025"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install PDM
        run: pip install --no-cache pdm

      - name: Install Dependencies
        run: pdm install -G test

      - name: Run Tests
        run: pdm run test
